# Generated by Django 3.2.7 on 2021-10-22 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
    ]
