# Generated by Django 3.2.7 on 2021-10-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20211022_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='mercado_pago_id',
            field=models.CharField(blank=True, db_index=True, default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='mercado_pago_status',
            field=models.CharField(blank=True, default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='mercado_pago_status_detail',
            field=models.CharField(blank=True, default=1, max_length=250),
            preserve_default=False,
        ),
    ]
